name: journeyrec_client
description: Journey Recorder
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  sqflite: ^2.3.0
  path: ^1.8.3
  geolocator: ^10.1.0
  async: ^2.11.0
  intl: ^0.19.0
  flutter_map: ^6.0.1
  url_launcher: ^6.2.0
  latlong2: ^0.9.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  uuid: ^4.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
